const db = require("../config/db");

// GET
exports.getFeatures = (req, res) => {\n  const { status } = req.query;\n  let sql = "SELECT * FROM features";\n  let params = [];\n  \n  if (status) {\n    sql += " WHERE status = ?";\n    params = [status];\n  }\n  \n  sql += " ORDER BY created_at DESC";\n  \n  db.query(sql, params, (err, results) => {\n    if (err) {\n      console.error('DB Error:', err.message);\n      return res.status(500).json({ error: "Failed to fetch features" });\n    }\n    res.json(results || []);\n  });\n};

// POST\nexports.addFeature = (req, res) => {\n  const { title, description, priority, status } = req.body;\n  \n  // Validation\n  if (!title || title.trim().length < 3) {\n    return res.status(400).json({ error: "Title is required (min 3 chars)" });\n  }\n  const validPriority = ['Low', 'Medium', 'High'];\n  const validStatus = ['Open', 'In Progress', 'Completed'];\n  \n  if (!validPriority.includes(priority)) {\n    return res.status(400).json({ error: "Invalid priority" });\n  }\n  if (!validStatus.includes(status)) {\n    return res.status(400).json({ error: "Invalid status" });\n  }\n  \n  const sql = "INSERT INTO features (title, description, priority, status) VALUES (?, ?, ?, ?)";\n  db.query(sql, [title.trim(), description || null, priority, status], (err) => {\n    if (err) {\n      console.error('Insert Error:', err.message);\n      return res.status(500).json({ error: "Failed to create feature" });\n    }\n    res.status(201).json({ message: "Feature created successfully" });\n  });\n};

// PUT\nexports.updateFeature = (req, res) => {\n  const { id } = req.params;\n  const { title, description, priority, status } = req.body;\n  \n  if (!title || title.trim().length < 3) {\n    return res.status(400).json({ error: "Title is required (min 3 chars)" });\n  }\n  const validPriority = ['Low', 'Medium', 'High'];\n  const validStatus = ['In Progress', 'Completed', 'Open'];\n  \n  if (!validPriority.includes(priority)) {\n    return res.status(400).json({ error: "Invalid priority" });\n  }\n  if (!validStatus.includes(status)) {\n    return res.status(400).json({ error: "Invalid status" });\n  }\n  \n  const sql = "UPDATE features SET title=?, description=?, priority=?, status=? WHERE id=?";\n  db.query(sql, [title.trim(), description || null, priority, status, id], (err, result) => {\n    if (err) {\n      console.error('Update Error:', err.message);\n      return res.status(500).json({ error: "Failed to update feature" });\n    }\n    if (result.affectedRows === 0) {\n      return res.status(404).json({ error: "Feature not found" });\n    }\n    res.json({ message: "Feature updated" });\n  });\n};

// DELETE\nexports.deleteFeature = (req, res) => {\n  const { id } = req.params;\n  \n  db.query("DELETE FROM features WHERE id=?", [id], (err, result) => {\n    if (err) {\n      console.error('Delete Error:', err.message);\n      return res.status(500).json({ error: "Failed to delete feature" });\n    }\n    if (result.affectedRows === 0) {\n      return res.status(404).json({ error: "Feature not found" });\n    }\n    res.json({ message: "Feature deleted" });\n  });\n};
